default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: office_development

test:
  <<: *default
  database: office_test

production:
  <<: *default
